### ISSUE TITLE
Running mykrobe-predict on ONT and Illumina data

### ISSUE THREAD

**Issue by nilay-p** [Mykrobe-tools/mykrobe#107]
Hi,
I have used "mykrobe predict" with both ONT (pre-processed with qcat: adapter trimmed) and Illumina data (raw data). 
But I am wondering if the pipeline includes pre-processing of raw data e.g. adapter trimming, trimming based on QC for both ONT and Illumina data. 
Do you think that I should have used also trimmed data of illumina?

Best,
Nilay

**Comment by iqbal-lab** [comment]
Hi there. It does not trim, but the use of kmers makes it very robust to them. I don't think you need to trim

**Comment by iqbal-lab** [comment]
i'm going to close this - feel free to reopen if you want. BTW we have just made a new release, v0.9.0, with updated lineage assignments
