### ISSUE TITLE
Meaning of hyphen in amino acid substitution report

### ISSUE THREAD

**Issue by flashton2003** [Mykrobe-tools/mykrobe#109]
Hello,

I've noticed that a few of my samples have something like a `pncA_T-12C`, and I was just wondering what the `-` between the `T` and `12` means?

To give an example of the full call, it's `pncA_T-12C-A2289253G:0:1013:5961`.

It also happens for isoniazid muations e.g. `fabG1_C-15X-C1673425T:0:447:3402`.

Thanks!

Phil

**Comment by martinghunt** [comment]
Hi Phil,

Negative numbers mean upstream of the gene. So those are 12bp and 15bp before the start of the pncA/fabG1 genes.

Martin

**Comment by flashton2003** [comment]
Awesome, thanks Martin! Sorry if I missed that in the documentation somewhere.

**Comment by martinghunt** [comment]
I'm sure you didn't miss it! Thanks for pointing it out though, I just added a note in the AMR prediciton output wiki page.
