### ISSUE TITLE
Overlapping/conflicting variants?

### ISSUE THREAD

**Issue by flashton2003** [Mykrobe-tools/mykrobe#110]
Hello,

I'm having trouble interpreting the reported variants for one of my samples. Three variants in pncA were reported:

pncA_T80TG-A2289162CA:76:470:3062,   pncA_G81GG-C2289161CC:51:470:3167, pncA_G82GG-C2289160CC:56:470:3146

Could you help me in interpreting these?

Thanks,

Phil

**Comment by martinghunt** [comment]
Hi Phil,

Those are all the same insertion of a G. In gene coords, they are T80TG, G81GG, G82GG. So the insertion is TGG -> TGGG, it's just that you can add that G in 3 "different" places.

This raises a question though. @iqbal-lab do you think next time we update the catalog we should remove duplicate representations of the same variant?

Martin

**Comment by flashton2003** [comment]
Thanks Martin, that makes sense.

**Comment by iqbal-lab** [comment]
ugh. yes. v sorry @flashton2003

**Comment by martinghunt** [comment]
ok, leaving this open as a reminder to do this when we make the next panel.

**Comment by flashton2003** [comment]
@iqbal-lab no problem Zam!

**Comment by mbhall88** [comment]
This is actually the same issue as #148. Closing this in favour of #148
