### ISSUE TITLE
"drug","susceptibility"  are "NA","N" in out.csv with fasta files

### ISSUE THREAD

**Issue by augustkx** [Mykrobe-tools/mykrobe#135]
Dear mykrobe team,

My input is fna files for tb, and the json output is such:

![Screenshot from 2021-10-04 02-25-10](https://user-images.githubusercontent.com/17084919/135778643-7ebae2ec-dc93-47e3-a0b9-23491ebaf75a.png)

My command is:
mykrobe predict -s SAMPLE -S tb -o out.csv -i 1773.18885.fna --format csv
mykrobe predict -s SAMPLE -S tb -o out.json -i 1773.18885.fna --format json

I am wondering what is wrong here?

**Comment by iqbal-lab** [comment]
Hi there 
Mykrobe does not support fasta file input. It takes raw sequencing data (fastq). Apologies for not having a better error message 
Regards 
Zam

**Comment by augustkx** [comment]
Hi there
Thanks very much for the reply.
But from here: https://github.com/Mykrobe-tools/mykrobe/wiki/AMR-Prediction#examples-of-basic-usage
it says:   -1 seq [seq ...], -i seq [seq ...], --seq seq [seq ...]
                        Sequence files (fasta,fastq,bam)

And may I ask why not fasta are not accepted? Are there any reasons?

Best, Kaixin

**Comment by iqbal-lab** [comment]
1. "it says:...Sequence files (fasta,fastq,bam)"----> this is an error in our wiki, apologies
2. Mykrobe uses the depth of coverage of reads on the susceptible and resistant alleles to draw inferences. It will not work with fasta
