### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by mbhall88** [Mykrobe-tools/mykrobe#143]
Additionally, the test suite isn't running on travis as we have a negative credit balance. Maybe I should open another issue to move on to github actions?

_Originally posted by @mbhall88 in https://github.com/Mykrobe-tools/mykrobe/issues/138#issuecomment-972533221_

Do we pay for travis? I don't really get the negative credit thing. Is there any impediment to us moving to Actions, aside from the creation of a new CI workflow config? (I have a number of python project Actions we can steal heavily from.)

**Comment by iqbal-lab** [comment]
We don't pay for Travis, maybe they changed to a paid model? Weird. I thought github actions got closed because too many people ran bitcoin mining in it

**Comment by mbhall88** [comment]
> I thought github actions got closed because too many people ran bitcoin mining in it

🤣 I had not heard that.

It is definitely still going - all my projects use it for CI.
