### ISSUE TITLE
Update mykrobe.com download links 0.9.0 -> 0.10.0

### ISSUE THREAD

**Issue by martinghunt** [Mykrobe-tools/mykrobe#157]
They are still pointing at 0.9.0 instead of 0.10.0

**Comment by mbhall88** [comment]
*0.11.0

**Comment by iqbal-lab** [comment]
Simon says this is fixed, will double check and close

**Comment by mbhall88** [comment]
Just checked and it seems to be pointing at 0.10.0 now
