### ISSUE TITLE
link to Hawkey 2020 publication on S sonnei panel?

### ISSUE THREAD

**Issue by kapsakcj** [Mykrobe-tools/mykrobe#165]
The Mykrobe wiki lists "Hawkey 2020" as the basis for the Shigella sonnei genotyping panel implemented in mykrobe. Could you provide a link to the publication?

I found this via google scholar, but I'm wondering if there is another publication that goes more in-depth on the genotyping panel.

https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008931

I'm curious to learn more about the lineage nomenclature for S sonnei to help make sense of the Mykrobe outputs.

Thanks!

**Comment by kapsakcj** [comment]
After a little bit more digging, I think I found the publication: https://www.nature.com/articles/s41467-021-22700-4

Still I think it would be helpful to link to the publication somewhere in the Mykrobe wiki.

Might also be useful to link to https://github.com/katholt/sonneityping as is done with Typhi & genotyphi

**Comment by iqbal-lab** [comment]
OMG @kapsakcj , i thought i had replied , many apologies! Sonneityping is already linked on the wiki here
https://github.com/Mykrobe-tools/mykrobe/wiki/AMR-Prediction
We should indeed link to the actual paper, will reply here when done

**Comment by iqbal-lab** [comment]
@martinghunt just added links here too https://github.com/Mykrobe-tools/mykrobe/wiki/Citing-mykrobe

**Comment by iqbal-lab** [comment]
ok to close this?

**Comment by kapsakcj** [comment]
Yes, thanks for adding those links and the citation, much appreciated!
