### ISSUE TITLE
Unexpected behaviour when using seq option multiple times

### ISSUE THREAD

**Issue by mbhall88** [Mykrobe-tools/mykrobe#168]
The `-1/-i/--seq` option takes the fastq file(s) to be analysed by mykrobe. This option can be used multiple times or just solo. However, I discovered that if it is used multiple times, only the last occurence is used. For example

- `-1 in.fq`: uses `in.fq`
- `-1 in.fq in2.fq`: uses `in.fq` and `in2.fq`
- `-1 in.fq -1 in2.fq`: uses `in2.fq` **only**

**Comment by iqbal-lab** [comment]
Wot

**Comment by martinghunt** [comment]
Just being picky, but the help does say to use the option once, not more than once ;) That said, it does make sense to allow of your 3 examples

**Comment by mbhall88** [comment]
Fair. Well we would either need to error if it is used twice, or allow it I guess...
