### ISSUE TITLE
Marginal genotyping calls

### ISSUE THREAD

**Issue by martinghunt** [Mykrobe-tools/mykrobe#21]
I'm seeing examples of false-positive calls on the Staph data. First couple we looked at were like this:

```
           "Rifampicin": {
                "predict": "R",
                "called_by": {
                    "rpoB_N474K-N474K": {
                        "variant": null,
                        "genotype": [
                            1,
                            1
                        ],
                        "genotype_likelihoods": [
                            -99999999,
                            -99999999,
                            -154.60248782950148
                        ],
                        "info": {
                            "coverage": {
                                "reference": {
                                    "percent_coverage": 68.75,
                                    "median_depth": 1,
                                    "min_non_zero_depth": 1,
                                    "kmer_count": 399
                                },
                                "alternate": {
                                    "percent_coverage": 100.0,
                                    "median_depth": 1,
                                    "min_non_zero_depth": 1,
                                    "kmer_count": 231
                                }
                            },
                            "expected_depths": [
                                158
                            ],
                            "contamination_depths": [],
                            "filter": "PASS",
                            "conf": 99999844
                        },
                        "_cls": "Call.VariantCall"
                    }
                }
            },
```
What do you make of it? Should we be calling "R" or saying no call because the coverage is so low?

**Comment by iqbal-lab** [comment]
This is an example of where the best model out of our options is still a very bad model. A model we have not considered until now (explicitly) is the idea that there is some other unknown allele at this site. Under such a model, you have bugger all coverage on all our known alleles. One could add this as a new model, or one can fudge it by having a final goodness-of-fit test which says "is the total coverage on our alleles acceptable"

**Comment by martinghunt** [comment]
Same data, but using the option `--model kemr_count` gives a susceptible call for RIF:
```
           "Rifampicin": {
                "predict": "S"
            },
```

and later in the output is this:

```
            "rpoB_N474K-AAT592250AAA": {
                "variant": "ref-N474K?var_name=AAT592250AAA&num_alts=3&ref=BX571856.1&enum=0&gene=rpoB&mut=N474K",
                "genotype": [
                    0,
                    0
                ],
                "genotype_likelihoods": [
                    -4191.66783889454,
                    -99999999,
                    -3630.7586198519884
                ],
                "info": {
                    "coverage": {
                        "reference": {
                            "percent_coverage": 68.75,
                            "median_depth": 1,
                            "min_non_zero_depth": 1,
                            "kmer_count": 399
                        },
                        "alternate": {
                            "percent_coverage": 18.75,
                            "median_depth": 0,
                            "min_non_zero_depth": 160,
                            "kmer_count": 536
                        }
                    },
                    "expected_depths": [
                        158
                    ],
                    "contamination_depths": [],
                    "filter": "LOW_PERCENT_COVERAGE",
                    "conf": 561
                },
                "_cls": "Call.VariantCall"
            },
            "rpoB_N474K-AAT592250AAG": {
                "variant": "ref-N474K?var_name=AAT592250AAG&num_alts=3&ref=BX571856.1&enum=0&gene=rpoB&mut=N474K",
                "genotype": [
                    0,
                    0
                ],
                "genotype_likelihoods": [
                    -3737.551803165563,
                    -99999999,
                    -4425.382086371027
                ],
                "info": {
                    "coverage": {
                        "reference": {
                            "percent_coverage": 68.75,
                            "median_depth": 1,
                            "min_non_zero_depth": 1,
                            "kmer_count": 399
                        },
                        "alternate": {
                            "percent_coverage": 100.0,
                            "median_depth": 1,
                            "min_non_zero_depth": 1,
                            "kmer_count": 231
                        }
                    },
                    "expected_depths": [
                        158
                    ],
                    "contamination_depths": [],
                    "filter": "PASS",
                    "conf": 688
                },
                "_cls": "Call.VariantCall"
            },
```

**Comment by iqbal-lab** [comment]
So in terms of false positives this is better for us, but it's still a bad call. With 1x on both alleles and expecting 150x, this should be a no-call.
I like the idea of a new competing model 

Could we add something like this here:

 https://github.com/Mykrobe-tools/mykrobe-atlas-cli/blob/9f5b7f4184a87da23592f14901c5585b223aca78/src/mykrobe/typing/typer/variant.py#L149

inside KmerCountGenotypeModel

>     def missing_allele_lik(self, variant_probe_coverage):
                missing_liks = []
            for expected_depth in self.expected_depths:
                missing_liks.append(
                    log_lik_R_S_kmer_count(
                        variant_probe_coverage.alternate_kmer_count,
                        variant_probe_coverage.reference_kmer_count,
                        0,
                        self.error_rate/3))
                )
            return max(het_missing)

That way, when we find something odd is going on with one site, we can refuse to make a call.

**Comment by iqbal-lab** [comment]
Do you think this makes sense @Phelimb ?

**Comment by martinghunt** [comment]
@Phelimb command line was:
`mykrobe predict sample staph --seq /nfs/leia/research/iqbal/mhunt/Mykrobe-eval.staph/Reads/ERR410095/ERR410095_1.fastq.gz /nfs/leia/research/iqbal/mhunt/Mykrobe-eval.staph/Reads/ERR410095/ERR410095_2.fastq.gz --output /hps/nobackup/iqbal/mhunt/Mykrobe-eval.staph.run_callers/caller_output/0/54/Mykrobe.staph/out.json`

**Comment by iqbal-lab** [comment]
which order are the likelihoods in the list? is the missing one the last in the list @martinghunt ?

**Comment by iqbal-lab** [comment]
I get it. So it looks like this does fix the problem (N=1) for the illumina model.
I propose, if the missing allele model wins for any mutation, then we no-call. Not sure if that is N or U or what. This does mean that when there is an R mutation confidently called in one place, but a missing allele elsewhere, we will no-call. But I think that is defensible.
