### ISSUE TITLE
Coll et al lineage/sub-lineage from Mykrobe

### ISSUE THREAD

**Issue by Phelimb** [Mykrobe-tools/mykrobe#47]
from https://github.com/iqbal-lab/Mykrobe-predictor/issues/150

I think it would be useful for Mykrobe to output the Coll et al lineage/sub-lineage, e.g. 2.2.1.1 from this manuscript. The SNPs/positions are available in the supplementary materials of the paper.

https://www.nature.com/articles/ncomms5812

**Comment by iqbal-lab** [comment]
I think this is probably superceded by https://github.com/philipwfowler/snpit

**Comment by martinghunt** [comment]
This is done, see #94
