### ISSUE TITLE
old url in setup.py

### ISSUE THREAD

**Issue by iqbal-lab** [Mykrobe-tools/mykrobe#54]
Is this meant to be there in setup.py?

` url='https://github.com/phelimb/mykrobe-atlas-cli`

also

` description='Mykrobe atlas'`

**Comment by mbhall88** [comment]
@iqbal-lab could you possibly use [permalinks](https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet) to the lines so we can be clear *exactly* what bits of code you're talking about?

**Comment by iqbal-lab** [comment]
sorry!
https://github.com/Mykrobe-tools/mykrobe/blob/9a818876de1b0db0b7f8f4399325e9a462a58573/setup.py#L56
