### ISSUE TITLE
Travis badges pointing to wrong repo

### ISSUE THREAD

**Issue by mbhall88** [Mykrobe-tools/mykrobe#58]
It seems that the build status badges in the README are pointing to https://travis-ci.org/Phelimb/mykrobe-atlas-cli

Should this be https://travis-ci.org/Mykrobe-tools/mykrobe-atlas-cli rather than a fork @Phelimb ?

**Comment by iqbal-lab** [comment]
also repo is now mykrobe/ no atlas-cli

**Comment by Phelimb** [comment]
I've removed as we don't have travis setup with the`Mykrobe-tools` org
