### ISSUE TITLE
X mutations in 201901 panel

### ISSUE THREAD

**Issue by AdmiralenOla** [Mykrobe-tools/mykrobe#63]
Dear mykrobe team,

In the 201901 probe set, many (most?) putative mutations are annotated as "X". For example, all resistance mutations at position 445 in the rpoB gene is now annotated as H445X.

Our clinicians are very interested in the actual amino acid change, so at the moment I am doing this with a fairly flimsy in-house script. What I'm wondering is if there are any plans to change the probe annotations back to their specific amino acid changes, or if there are any other tricks to getting the actual changes annotated in the output?

Best regards,
Ola Brynildsrud
Norwegian Institute of Public Health

**Comment by iqbal-lab** [comment]
That's a fair point, we'd better add that as an enhancement

**Comment by martinghunt** [comment]
This will be fixed on the master branch when #104 is merged. But there have been changes to how the panel data is downloaded/installed by mykrobe. There will be very soon a new release, at which point the documentation will get updated to describe the new installation of panels. So I advise to wait for the new mykrobe release to get this fix.
