### ISSUE TITLE
susceptibility

### ISSUE THREAD

**Issue by Adelaam** [Mykrobe-tools/mykrobe#67]
Hello,

I am trying to get susceptibility for a M. tuberculosis genome, the output is giving me this:
tb_sample_id": {
        "susceptibility": {},
        "phylogenetics": {
            "phylo_group": {
                "Mycobacterium_tuberculosis_complex": {
                    "percent_coverage": 96.699,
                    "median_depth": 1

But not antibiotics results, do you why?

Thank you

**Comment by iqbal-lab** [comment]
it says the median depth is 1 - it won't make predictions with that little data.

**Comment by Adelaam** [comment]
I used a fasta file genome, is because of that? Or because the genome is too small.

Thank you.

**Comment by iqbal-lab** [comment]
ah yes, it doesn't support fasta file genomes - it is designed to take raw sequencing data. i'm closing this, please open a new one if you have an issue when using raw sequence data
