### ISSUE TITLE
Unsure how to add a resistance mutation

### ISSUE THREAD

**Issue by jg95ae** [Mykrobe-tools/mykrobe#68]
Hello Mykrobe team,

I am running Mykrobe to predict susceptibilities in S. aureus, and I would like to add a mutation that predicts low-level resistance to mupirocin (ileS V588F). Looking at the README it's not clear how I go about this. It's a point mutation so I can add a variant by coordinates for that gene. Does this fall under the "Building a custom probe set"?  If so then I'm not sure about the db_name? Do I create this as a separate database and run it independently of 'mykrobe predict staph' or can I incorporate it in and run this new resistance prediction target with the rest? If that is the case what is the db_name that contains the default staph predictions?

Thank you in advance for your assistance with this!

Best,
Jen

**Comment by jg95ae** [comment]
As an update, I've sorted out how to build a custom probe set....I think! But if I run mykrobe predict with panel set to custom and the custom filepath for the probe and json files it outputs the results of the staph-amr-bradley_2015-feb-17-2017 panel and not my custom panel

Looking at page 20 in the new Wellcome article it states that the "species" parameter can be "tb" or "staph" to use the built-in panels or "custom" for a user generated panel.  If I try running mykrobe predict with "custom" as the species which is what I take that to mean it tells me I have to input "staph" or "tb". When I put "staph" for the species I'm getting the results for the default panel as mentioned above and not my custom panel.

Am I misunderstanding something? Missed a step in creating the custom probes?

Jen

**Comment by martinghunt** [comment]
Hi Jen,
The command should be like this:

```
mykrobe predict sample_name staph \
  --seq reads.fastq.gz \
  --panel custom \
  --custom_variant_to_resistance_json /full/path/to/panel.json \
  --custom_probe_set_path /full/path/to/probes.fasta.gz
```
In testing this, I just discovered that the `--custom_*` options do need the full path to the filenames, otherwise you'll get an error like `ValueError: Could not find a panel at ...`. 

Hope that solves it for you,
Martin

**Comment by jg95ae** [comment]
Hi Martin,

Thank you for looking into this for me. These commands match what I had been trying without any luck. It still seems to be ignoring my custom panel and probes. It is just outputing a .csv with the default staph panel rather than my custom panel. 

I'm looking through the documentation again in the new paper. The one thing I didn't do is add background variants as it looks like an optional step. Is that correct that I don't need to run code related to a database or I've misunderstood?

Thank you,
Jen

**Comment by martinghunt** [comment]
Turns out that there was a bug where mykrobe was ignoring those options when the species was staph (but used them if species was tb). I've fixed that and got a custom panel to work with staph. The change is there on the master branch. Could you give it a go please?

**Comment by jg95ae** [comment]
Hi Martin,

I've got it working now! Although the amr.py file was still the old one when I installed v0.8.0 (which I had a fair bit of trouble installing unfortunately related to mccortex issues) so I had to manually replace the file to get it to work. But eventually it did work.

Along with point mutations I'm also trying to predict resistance based on the presence of genes known to confer resistance. I'm not clear on how to add these to a custom panel. I tried to do it a bit manually by adding to my current custom panel but when I tried to run mykrobe predict I received the following error:
AttributeError: 'NoneType' object has no attribute 'split'

Could I ask for some direction on how to add custom presence/absence genes for resistance prediction?

Thank you!!
Jen

**Comment by martinghunt** [comment]
Hi Jen,

We've been planning on rewriting the documentation. I just started by writing docs on how to make a custom panel. It's here:
https://github.com/Mykrobe-tools/mykrobe/wiki/Custom-Panels

I'm not sure what you ran to get that error, but hopefully that new doc fixes it for you. Please let me know if anything is not clear and I can edit it.

Martin

**Comment by jg95ae** [comment]
Excellent thank you this is very helpful. It seems I had a small issue in my custom probes fasta file. I'm all sorted now.

I appreciate your help with all of this!

Jen
