### ISSUE TITLE
Could not find a panel at anaconda3 panels folder

### ISSUE THREAD

**Issue by shashibioinfo143** [Mykrobe-tools/mykrobe#69]
Hi,
I tried to install mykrobe in conda environment via command **conda install -c bioconda mykrobe** on ubuntu 16.04 version. Below command shows error that it couldn't able to find panels folder. Can you please help me to resolve the issue.

**mykrobe predict tb_Test_15 tb -1 Test_15_full.fastq --format csv --output Test_15_Mykrobe_results.csv
INFO:mykrobe.cmds.amr:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-hunt-probe-set-jan-03-2019.fasta.gz**
Traceback (most recent call last):
  File "/home/fmr/anaconda3/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/parser.py", line 40, in run_subtool
    run(parser, args)
  File "/home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/cmds/amr.py", line 256, in run
    cp.run()
  File "/home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/typing/typer/genotyper.py", line 73, in run
    self._run_cortex()
  File "/home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/typing/typer/genotyper.py", line 90, in _run_cortex
    self.mc_cortex_runner.run()
  File "/home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/cortex/mccortex.py", line 183, in run
    self._check_panels()
  File "/home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/cortex/mccortex.py", line 195, in _check_panels
    panel.filepath)
ValueError: Could not find a panel at /home/fmr/anaconda3/lib/python3.7/site-packages/mykrobe/data/panels/tb-species-170421.fasta.gz
![Screenshot from 2019-11-05 14-31-48](https://user-images.githubusercontent.com/54669756/68193485-1b266d00-ffd9-11e9-81e2-ff2206010276.png)

Thank you

**Comment by shashibioinfo143** [comment]
hi have checked below links but couldn't solve the error
https://github.com/Mykrobe-tools/mykrobe/issues/46

https://github.com/bioconda/bioconda-recipes/issues/13784

**Comment by shashibioinfo143** [comment]
I have checked below links but still it shows same error
https://github.com/bioconda/bioconda-recipes/issues/13784
https://github.com/bioconda/bioconda-recipes/pull/14175

**Comment by mbhall88** [comment]
Which version of `conda` are you using, and which version of `mykrobe` do you have installed in the conda environment?

**Comment by shashibioinfo143** [comment]
> Which version of `conda` are you using, and which version of `mykrobe` do you have installed in the conda environment?

Hi Michael,

I'm using conda 4.7.12
Mykrobe 0.6.1

**Comment by mbhall88** [comment]
Hmm, that isn't the latest version of `mykrobe` from bioconda (latest is v0.7.0).

Could you try [updating](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#updating-packages) with `conda update mykrobe`

**Comment by shashibioinfo143** [comment]
I tried to update it but still shows the same version
![Screenshot from 2019-11-06 17-01-24](https://user-images.githubusercontent.com/54669756/68294917-3ff11200-00b7-11ea-99bf-bd3a3b71e727.png)

**Comment by mgro** [comment]
I have the same problem that `conda update mykrobe` still only gets mykrobe version 0.6.1?

**Comment by mbhall88** [comment]
Ok, there seem to be some weird conflicts which mean conda won't install the latest mykrobe (v0.7.0). I have raised an issue about this as I can't figure out how to fix it https://github.com/bioconda/bioconda-recipes/issues/18528.

@mgro note the following
> I am experiencing the same error as shashibioinfo143, probably caused by the older mykrobe version (0.6.1). conda update mykrobe still only gets mykrobe version 0.6.1? Installing with pip works well.

This will install a very old version of mykrobe (not recommended).

**Comment by shashibioinfo143** [comment]
Hi Micheal,
I tried to install directly before using conda environment last week itself but I got error related to mccortex(screenshot attached).
Thanks
![Screenshot from 2019-11-08 08-59-41](https://user-images.githubusercontent.com/54669756/68447597-8903ac00-0206-11ea-9e02-116b7385446a.png)
![Screenshot from 2019-11-08 08-59-57](https://user-images.githubusercontent.com/54669756/68447608-8e60f680-0206-11ea-8542-a8d433667790.png)
![Screenshot from 2019-11-08 09-00-05](https://user-images.githubusercontent.com/54669756/68447616-9325aa80-0206-11ea-9530-6185771ff262.png)

**Comment by mbhall88** [comment]
Could you show me the permissions on the cortex binary you are specifying? 

Did you install mykrobe with `sudo`?

**Comment by mbhall88** [comment]
I have been able to fix this issue by following the steps in https://github.com/bioconda/bioconda-recipes/issues/18528#issuecomment-552062221.  

The key is having your conda channels set up correctly, as outlined in the ["Getting Started" section](https://bioconda.github.io/user/install.html#set-up-channels) of the bioconda docs.

So the following installed the latest (correct) version of `mykrobe` for me.

```sh
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create -n mykrobe mykrobe
conda activate mykrobe
```

Let me know if this works for you.

**Comment by shashibioinfo143** [comment]
> I have been able to fix this issue by following the steps in [bioconda/bioconda-recipes#18528 (comment)](https://github.com/bioconda/bioconda-recipes/issues/18528#issuecomment-552062221).
> 
> The key is having your conda channels set up correctly, as outlined in the ["Getting Started" section](https://bioconda.github.io/user/install.html#set-up-channels) of the bioconda docs.
> 
> So the following installed the latest (correct) version of `mykrobe` for me. (_Note: the channels **must** be added in this exact order_)
> 
> ```shell
> conda config --add channels defaults
> conda config --add channels bioconda
> conda config --add channels conda-forge
> conda create -n mykrobe mykrobe
> conda activate mykrobe
> ```
> 
> Let me know if this works for you.

Thanks a lot for the help. !!!
Its working fine now.
