### ISSUE TITLE
Couldnt able to install Mykrobe via conda in windows 7

### ISSUE THREAD

**Issue by shashibioinfo143** [Mykrobe-tools/mykrobe#70]
Hi im trying to install Mykrobe via anaconda prompt 3 version but it shows below error can anyone please help me to resolve the same

Thank you

(base) C:\Users\TFMR2014>conda install -c bioconda mykrobe
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mykrobe

Current channels:

  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

![conda_error](https://user-images.githubusercontent.com/54669756/68198979-1ff01e80-ffe3-11e9-91cc-af42ab60c68a.png)

**Comment by mbhall88** [comment]
I believe this is because the bioconda recipe we have doesn't have a Windows install `.bat` file. i.e we don't have support for Windows at the moment.

However, you should be able to install the ["normal" way](https://github.com/Mykrobe-tools/mykrobe#installation). Feel free to put in a PR with a Windows bioconda recipe if you like.
