### ISSUE TITLE
depth of Resistant mutation not generated in .csv format

### ISSUE THREAD

**Issue by shashibioinfo143** [Mykrobe-tools/mykrobe#73]
Hi Martin,

This is regarding the Mykrobe V0.7.0 results.

In the current (0.7.0) version in Output .CSV format it doesn't give **depth of Resistant mutation** unlike previous version, but its available in .json format.

how to get depth value for Resistant mutation in .CSV format?

or 

Can we generate both format(.csv and .json) files in one command?

And one more question is for one sample **Pyrazinamide** susceptibility is r, what does it mean?

Please do give your comments on the above query

Thank you

**Comment by nilay-p** [comment]
Hi,
I am also wondering, if it is possible to generate both format files in one command.
Thanks..

**Comment by martinghunt** [comment]
I've changed it so if you use `--output foo --format json_and_csv`, then it will write `out.json` and `out.csv`. This is on the master branch, and will be in the next release.

@shashibioinfo143 - "r" means a minor allele call. There's a discussion about it in issue #84.
