### ISSUE TITLE
option for multiprocessing?

### ISSUE THREAD

**Issue by foamy1881** [Mykrobe-tools/mykrobe#74]
Is there an option to process more than one BAM alignment inside a folder? and produce a single report for it?

**Comment by iqbal-lab** [comment]
You can pass in multiple sequence files (space separated as I recall).

**Comment by foamy1881** [comment]
Problem is I have more than 500 plus isolates to process.. I have limited knowledge in bioinformatics so anyone can help me with some looping?

**Comment by RaSieb** [comment]
They are a bit older, and written for fastq files, but maybe you can adapt these batch processing scirpts to work with BAM files? 
https://github.com/RaSieb/batchMykrobe

**Comment by iqbal-lab** [comment]
ok i'm closing this. I misunderstood the question - if you are asking how to automate running mykrobe on many different samples/fastq - i recommend bash, GNU parallels, nextflow or snakemake. Biostars is generally a good place to look, and to ask questions
https://www.biostars.org/p/63816/
