### ISSUE TITLE
Running Mykrobe predict on both reverse and forward fastq files

### ISSUE THREAD

**Issue by mgro** [Mykrobe-tools/mykrobe#75]
Hi Michael,

from the options it is a bit unclear on how to deal with paired end sequences and it seems that Mykrobe takes either the forward or reverse fastq file. Is it best practice to first combine the two reads into one fastq file or can you provide both files to let mykrobe predict run on?

Thanks,
Matthias

**Comment by iqbal-lab** [comment]
Hi Matthias - you can pass in both fastq in using

```--seq file1.fq file2.fq```

It doesnt care about the order.

**Comment by iqbal-lab** [comment]
closing
