### ISSUE TITLE
Combining all mykrobe result into a table?

### ISSUE THREAD

**Issue by foamy1881** [Mykrobe-tools/mykrobe#76]
Is there a way to combine all mykrobe result into one table for reporting?

**Comment by iqbal-lab** [comment]
```--format csv``` gets you very close to a table

**Comment by mbhall88** [comment]
@foamy1881 does the CSV format provide you with an output format akin to what you are after? If not, what other information is it missing?

**Comment by mbhall88** [comment]
Closing this as no reply. Feel free to reopen if you still have this issue.
