### ISSUE TITLE
WARNING:mykrobe.cortex.mccortex:Not running mccortex.  & TypeError: Instantiating a document with positional arguments is not supported.

### ISSUE THREAD

**Issue by nilay-p** [Mykrobe-tools/mykrobe#77]
Hi,
I managed to install mykrobe v0.7.0 (although I still had to copy the panel data to "~ /python3.7/site-packages/mykrobe/data/") through conda.
I am trying to run the program but I encountered the following issue;

WARNING:mykrobe.cortex.mccortex:Not running mccortex. Force flag is false and coverage temp file exists
Traceback (most recent call last):
  File "/Users/nilay/miniconda3/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/Users/nilay/miniconda3/lib/python3.7/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/Users/nilay/miniconda3/lib/python3.7/site-packages/mykrobe/parser.py", line 42, in run_subtool
    run(parser, args)
  File "/Users/nilay/miniconda3/lib/python3.7/site-packages/mykrobe/cmds/amr.py", line 274, in run
    phylogenetics = species_predictor.run()
  File "/Users/nilay/miniconda3/lib/python3.7/site-packages/mykrobe/metagenomics/phylo.py", line 65, in run
    return MykrobePredictorPhylogeneticsResult(self.out_json["phylogenetics"])
  File "/Users/nilay/miniconda3/lib/python3.7/site-packages/mongoengine/base/document.py", line 79, in __init__
    "Instantiating a document with positional arguments is not "
TypeError: Instantiating a document with positional arguments is not supported. Please use `field_name=value` keyword arguments.

Could you please help me to resolve it?
Regards,
Nilay

**Comment by sagrudd** [comment]
I have also encountered this issue - Ubuntu 19.04 - Python 3.7.3

**Comment by martinghunt** [comment]
Thanks for letting us know. I am working on it. I can reproduce the TypeError with Ubuntu 18.04 + Python 3.6.9 (tox tests fail).

**Comment by nilay-p** [comment]
Hi,
I have re-installed mykrobe through conda. Mccortex issue is solved but I am still having the same mongoengine TypeError. Could you please guide me to fix it?

**Comment by mbhall88** [comment]
@nilay-p I have updated the conda build of mykrobe for v0.8.0 - could you please try this out and see if it fixes the issue? The previous build for v0.8.0 was pulling in an old version of monogengine which, I think, was leading to you experiencing the same issue still.

**Comment by mbhall88** [comment]
Assuming this is resolved as no response from @nilay-p. Please reopen if this is still a problem.
