### ISSUE TITLE
example data please

### ISSUE THREAD

**Issue by sagrudd** [Mykrobe-tools/mykrobe#79]
I am trying to review the mykrobe functionality for some nanopore sequence data - I am not getting any error messages but the results appear a little sparse. 

Would it be possible to include some example data (or a link to some appropriate data) with the source so that the functionality of the code can be established using a known dataset - I can then leap into the unknown with a little more confidence.

Thanks - Stephen

**Comment by iqbal-lab** [comment]
this link gives the ENA accessions of the nanopore data used in the Mykrobe paper, and the results we obtained by running it
https://figshare.com/articles/ont_tsv/7605443
(the paper is here https://wellcomeopenresearch.org/articles/4-191/v1 )

**Comment by sagrudd** [comment]
Awesome, thanks!

**Comment by sagrudd** [comment]
@iqbal-lab - are these ENA data public? A search for the listed accession ```ERS3036286``` does not yet return any results.

**Comment by martinghunt** [comment]
@sagrudd Sorry about that, I just made all the data public. It takes a day for that to filter through to the public website.

**Comment by sagrudd** [comment]
data is now available at the ENA, thanks!
