### ISSUE TITLE
Anyone know where to get total SNPS being called for each isolate? 

### ISSUE THREAD

**Issue by foamy1881** [Mykrobe-tools/mykrobe#87]
I'm trying to obtain total number of SNPs being called via mykrobe. Where can i obtain the information? The result summary table only provide the drug resistance profile and other coverage details.

**Comment by martinghunt** [comment]
mykrobe works using "probe" sequences containing variants from its catalog of mutations that cause drug resistance. It does not use the whole reference genome, only the regions of the genome where the mutations of interest are. This means it cannot report something like "here are all the SNPs between the reads and the reference genome". In the JSON output, mykrobe reports all of the mutations that it found from its catalog of mutations, and the depth etc.
