### ISSUE TITLE
"Referenced from: /Applications/Mykrobe.app/Contents/Resources/bin/Python (which was built for Mac OS X 10.13)"

### ISSUE THREAD

**Issue by davidjstudholme** [Mykrobe-tools/mykrobe#90]
Dear Mykrobe team,

everything is working fine for me, but a colleague is having problems.

She downloaded and installed software from: https://github.com/Mykrobe-tools/mykrobe/releases/download/v0.8.1/Mykrobe-0.8.1.dmg

She is using macOS Sierra version 10.12.6.

When she loads .json results that I generated for her, all is fine.

But when she tries to analyse a fastq or bam file (files that work fine for me) then she sees four error messages:

"Referenced from: /Applications/Mykrobe.app/Contents/Resources/bin/Python (which was built for Mac OS X 10.13)"

"Expected in: /usr/lib/libSystem.B.dylib"

"in /Applications/Mykrobe.app/Contents/Resources/bin/Python"

"Process exit unexpectedly with code 255"

Cheers,

David

**Comment by martinghunt** [comment]
Hi David,

This may be hard to diagnose. Our first guess is that she may not have enough RAM. Could you please let us know the specs of the machine by pasting what "About This Mac" says?

I would however recommend to upgrade the OS if it's possible to do so. Sierra is no longer supported by Apple, and the old OS may also be the reason that mykrobe failed.

Martin

**Comment by davidjstudholme** [comment]
Thank you, Martin.

Please see attached screenshot of About this Mac:

MacBook Air (13-inch, Early 2015)
Processor 1.6 GHz Intel Core i5
Memory 8 GB 1600 MHz DDR3
Graphics Intel HD Graphics 6000 1536 MB

I am cc’ing this to my colleague who is having the issue. I understand that you cannot reasonably be expected to ensure Mykrobe’s compatibility on old unsupported operating systems!

Are older releases of Mykrobe still available as that might be a good temporary solution until an operating system upgrade is possible?

Best wishes,

David

**Comment by martinghunt** [comment]
Hi David,

OK, so the specs look fine. We're going to have a go at building a version for 10.12 - this may take a few days so please bear with us. Sorry, but there are no older versions available that have the up to date variant catalog and  methods matching the new publication.

Martin

**Comment by davidjstudholme** [comment]
Thanks very much indeed, Martin. Much appreciated. It is not urgent but it will certainly be helpful.

Regarding legacy versions of Mykrobe, given that the Nature Comms. Paper is still in the public domain, for repeatability purposes should not the versions described in that paper also still be available?

Best wishes,

David

**Comment by iqbal-lab** [comment]
The nature communications paper refers to this repository https://github.com/iqbal-lab/Mykrobe-predictor, which still exists, is archive ved and read-only. The old versions are still there. But as of this year we've moved to a new implementation

**Comment by davidjstudholme** [comment]
Brilliant, thank you, Zam. I found the old releases here: https://github.com/iqbal-lab/Mykrobe-predictor/releases

Best wishes,

David

**Comment by martinghunt** [comment]
Hi David,

Sorry, but we're not able to support mac os 10.12. It's proving to be too difficult to build because of out of date software.

Best wishes,
Martin

**Comment by davidjstudholme** [comment]
No problem, Martin. That’s a perfectly reasonable position.

Thank you,

David
