### ISSUE TITLE
Remove detox from requirements

### ISSUE THREAD

**Issue by mbhall88** [Mykrobe-tools/mykrobe#92]
detox is unmaintained and incompatible with tox > 3.6

As far as I can tell, we don't actually use it anywhere either?

In addition, the [github repo is archived](https://github.com/tox-dev/detox).

> detox was a plugin for tox to enable parallel environment execution. tox 3.7 added a native possibility to do this (tox -p|--parallel) and effectively supercedes detox.

Given all this are we happy to remove it from the requirements to avoid possible issues further down the road?

**Comment by martinghunt** [comment]
Good spot. I agree, can't see it being used anywhere.
