### ISSUE TITLE
Update MTBC lineage to latest comas/gagneux snps

### ISSUE THREAD

**Issue by iqbal-lab** [Mykrobe-tools/mykrobe#94]
Use this simple table, one snp assigns each lineage and sublineage.

[inaki_snps_for_typing_lineages.xlsx](https://github.com/Mykrobe-tools/mykrobe/files/4616797/inaki_snps_for_typing_lineages.xlsx)

**Comment by iqbal-lab** [comment]
Currently we have probes in tb-species-170421.fasta on figshare. Our system is intrinsically hierarchical, so should be ok mapping this kind of thing


lineage | Position | Gene coord. | Allele change
-- | -- | -- | --
lineage1 | 615938 | 1104 | G/A
lineage1.1 | 4404247 | 1056 | G/A
lineage1.1.1 | 3021283 | 711 | G/A
lineage1.1.1.1 | 3216553 | 339 | G/A
lineage1.1.2 | 2622402 | 51 | G/A

to a lineage here

https://github.com/Mykrobe-tools/mykrobe/blob/master/src/mykrobe/metagenomics/phylo.py

**Comment by iqbal-lab** [comment]
Validation samples @martinghunt !!

lineage1.1.1	SRR6797804
lineage1.1.2	SRR6964563
lineage1.1.3	SRR6797825
lineage1.2.1	ERR270695
lineage1.2.2	ERR117616
lineage2.1	ERR270697
lineage2.2.1	SRR6832560
lineage2.2.10	ERR228068
lineage2.2.2	ERR234128
lineage2.2.3	ERR275194
lineage2.2.4	ERR351920
lineage2.2.5	ERR234193
lineage2.2.6_RD150	ERR234140
lineage2.2.7	SRR6650276
lineage2.2.8_RD142	SRR6797789
lineage2.2.9	SRR6484910
lineage3.1.1	ERR176648
lineage3.1.2	ERR270781
lineage4.1.1	SRR6650384
lineage4.1.2	ERR1465801
lineage4.1.3	ERR234198
lineage4.10	SRR6785535
lineage4.2.1	ERR144624
lineage4.2.2	SRR671832
lineage4.3.1	ERR1193830
lineage4.3.2	SRR6896506
lineage4.3.3	SRR6855976
lineage4.3.4	ERR161193
lineage4.4.1	ERR228067
lineage4.4.2	SRR671725
lineage4.5	ERR117623
lineage4.6.1	ERR1199080
lineage4.6.2	ERR278539
lineage5	ERR2383621
lineage6	ERR233366
lineage7	ERR159957
lineageBovis ERR161048
lineageCaprae SRR5216774

**Comment by iqbal-lab** [comment]
Update, new spreadsheet with 3 animal lineages
[inaki_snps_for_typing_lineages_incl_animals.xlsx](https://github.com/Mykrobe-tools/mykrobe/files/4628278/inaki_snps_for_typing_lineages_incl_animals.xlsx)

and validation samples for the extra lineages
A1    ERR970409
A2    SRR1239339
A3    ERR015582

**Comment by mbhall88** [comment]
Cross-posting from https://github.com/mbhall88/head_to_head_pipeline/issues/11#issuecomment-636656826

Using the SNPs that [Alvaro and Inaki gave us](https://github.com/Mykrobe-tools/mykrobe/issues/94#issue-616775470) I find two where the reference allele does not match the base at that position in H37Rv.

## Lineage 4.3
```
lineage              lineage4.3
position                1480024
gene_coord                  NaN
allele_change               C/T
codon_number                541
codon_change                NaN
amino_acid_change           NaN
locus_id                 Rv1318
gene_name                     -

H37Rv base at that position: G
```
When I dig into the [source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5238942/) that they got their L4-defining SNPs from I find that the position is correct - 1480024 - and the allele change is actually `G/T`. So it seems they entered the ref allele incorrectly in the version of the spreadsheet they sent us. If we change the ref allele from `C->G` in our sheet, then everything checks out for this sublineage.

## Lineage 4.10
```
lineage              lineage4.10
position                 1692141
gene_coord                   NaN
allele_change                C/A
codon_number                 NaN
codon_change                 NaN
amino_acid_change            NaN
locus_id                     NaN
gene_name                    NaN

H37Rv base at that position: A
```
The position is correct for this one and according to [Supp. Table 2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5238942/bin/NIHMS70062-supplement-Supplementary_Tables_1-9.pdf) the ref and mutant alleles are the same as in the Comas spreadsheet `C->A`. H37Rv has an `A` at this position. I guess this is the discrepancy that Kerri found, but I just wanted to document it.

**Comment by iqbal-lab** [comment]
Looks like we can use cobF gene as marker for lineage 8.
https://twitter.com/con_meehan/status/1270349135833686016?s=19

**Comment by martinghunt** [comment]
What do we do with the snp at 1692141? Should it be A->C?

**Comment by mbhall88** [comment]
> What do we do with the snp at 1692141? Should it be A->C?

See https://github.com/mbhall88/head_to_head_pipeline/issues/11#issuecomment-640374147 for a discussion of this.

**Comment by martinghunt** [comment]
ok, so for the record, the implementation here needs to allow defining lineage SNPs as being either the ref or alt allele. Not just assume that it's alt that implies whatever lineage.

For A1692141C, it's having A(=ref) that defines lineage 4.10, not C(=alt).

**Comment by martinghunt** [comment]
Will soon be sending PR to close this issue...

Note: had to add in backgrounds when running make probes to get all lineage test samples to work. There are a few lineage SNPs within a kmer of common SNPs.

Attaching two files:
`lineage_snps.txt` - file defining the lineages and SNPs that will be used in the next mykrobe release. It is used as input to make-probes.
`test_samples.txt` - list of test samples with expected lineage call.

On my test branch (soon to be merged in to master), mykrobe gets all calls correct on those samples. Only differences are where mykrobe calls a sublineage of the correct lineage. These are:
```
sample      expect        mykrobe_call
SRR6650384  lineage4.1.1  lineage4.1.1.3
ERR1465801  lineage4.1.2  lineage4.1.2.1
SRR6896506  lineage4.3.2  lineage4.3.2.1
ERR161193   lineage4.3.4  lineage4.3.4.2.1
ERR228067   lineage4.4.1  lineage4.4.1.1
ERR1199080  lineage4.6.1  lineage4.6.1.1
```

[lineage_snps.txt](https://github.com/Mykrobe-tools/mykrobe/files/5306353/lineage_snps.txt)
[test_samples.txt](https://github.com/Mykrobe-tools/mykrobe/files/5306354/test_samples.txt)
