### ISSUE TITLE
Version number is not inline with actual release version

### ISSUE THREAD

**Issue by mbhall88** [Mykrobe-tools/mykrobe#97]
https://github.com/Mykrobe-tools/mykrobe/blob/42d56a43d48fd5793708ace327dff339594c5b08/src/mykrobe/version.py#L1

we are on version 0.8.2 at the moment. I guess it is best to fix this when resolving #96

**Comment by martinghunt** [comment]
Yep, fixed at the same time as resolving #96 . Release is version is now v0.8.2 on both the releases page and in the code.
